#ifndef PINS_H
#define PINS_H

#include <Arduino.h>


#define PIN_FINGER_MOD_OUTPUT_1 1
#define PIN_FINGER_MOD_OUTPUT_2 2
#define PIN_FINGER_MOD_OUTPUT_3 42
#define PIN_FINGER_MOD_OUTPUT_4 41
#define PIN_FINGER_MOD_OUTPUT_5 40
#define PIN_FINGER_MOD_OUTPUT_6 39

#define PIN_FINGER_MOD_INPUT_1 38
#define PIN_FINGER_MOD_INPUT_2 37
#define PIN_FINGER_MOD_INPUT_3 36
#define PIN_FINGER_MOD_INPUT_4 35

#define PIN_FINGER_MOD_WHEEL_A 45
#define PIN_FINGER_MOD_WHEEL_B 48
#define PIN_FINGER_MOD_WHEEL_GND 0


#define PIN_THUMB_MOD_LED_V 43
#define PIN_THUMB_MOD_LED_DATA 44

#define PIN_THUMB_MOD_OUTPUT_1 18
#define PIN_THUMB_MOD_OUTPUT_2 8
#define PIN_THUMB_MOD_OUTPUT_3 3

#define PIN_THUMB_MOD_INPUT_1 4
#define PIN_THUMB_MOD_INPUT_2 5
#define PIN_THUMB_MOD_INPUT_3 6
#define PIN_THUMB_MOD_INPUT_4 7

#define PIN_THUMB_MOD_JOYSTICK_V 46
#define PIN_THUMB_MOD_JOYSTICK_Y 9
#define PIN_THUMB_MOD_JOYSTICK_X 10




// old pins configuration
// #define PIN_FINGER_MOD_OUTPUT_1 1
// #define PIN_FINGER_MOD_OUTPUT_2 2
// #define PIN_FINGER_MOD_OUTPUT_3 42
// #define PIN_FINGER_MOD_OUTPUT_4 41
// #define PIN_FINGER_MOD_OUTPUT_5 40
// #define PIN_FINGER_MOD_OUTPUT_6 39

// #define PIN_FINGER_MOD_INPUT_1 38
// #define PIN_FINGER_MOD_INPUT_2 37
// #define PIN_FINGER_MOD_INPUT_3 36
// #define PIN_FINGER_MOD_INPUT_4 35

// #define PIN_FINGER_MOD_WHEEL_A 47
// #define PIN_FINGER_MOD_WHEEL_B 21



// #define PIN_THUMB_MOD_OUTPUT_1 18
// #define PIN_THUMB_MOD_OUTPUT_2 8
// #define PIN_THUMB_MOD_OUTPUT_3 3

// #define PIN_THUMB_MOD_INPUT_1 4
// #define PIN_THUMB_MOD_INPUT_2 5
// #define PIN_THUMB_MOD_INPUT_3 6
// #define PIN_THUMB_MOD_INPUT_4 7


// #define PIN_THUMB_MOD_JOYSTICK_X 6
// #define PIN_THUMB_MOD_JOYSTICK_Y 7

// #define PIN_BATTERY_VOLTAGE 14




#endif
